# app.py
# This is the MAIN file — it runs the entire web app
# It connects eda.py, query_engine.py, and report.py together
# into one clean Streamlit interface

import streamlit as st
import pandas as pd
from eda import run_eda
from query_engine import query_dataframe
from report import generate_report, export_pdf

# App settings
st.set_page_config(
    page_title="AI Data Analyst",
    page_icon="🤖",
    layout="wide"
)

# App title
st.title("🤖 AI-Powered Data Analyst")
st.caption("Upload any dataset → Get instant analysis, ask questions in plain English, generate reports")

# Sidebar file upload
st.sidebar.title("📁 Upload Your Dataset")
uploaded_file = st.sidebar.file_uploader(
    "Supports CSV and Excel files",
    type=["csv", "xlsx"]
)

# Main app — only runs after file is uploaded
if uploaded_file is not None:

    # Load the file into pandas
    if uploaded_file.name.endswith(".csv"):
        df = pd.read_csv(uploaded_file)
    else:
        df = pd.read_excel(uploaded_file)

    # Show success in sidebar
    st.sidebar.success(f"✅ File loaded successfully!")
    st.sidebar.info(f"📐 {df.shape[0]} rows × {df.shape[1]} columns")

    # 3 tabs for 3 features
    tab1, tab2, tab3 = st.tabs([
        "📊 Auto Analysis",
        "💬 Ask Your Data",
        "📄 Generate Report"
    ])

    # TAB 1 — Auto EDA
    with tab1:
        st.header("📊 Automatic Data Analysis")
        run_eda(df)

    # TAB 2 — Natural Language Querying
    with tab2:
        st.header("💬 Ask Anything About Your Data")
        st.caption("Type a question in plain English — AI writes and runs the code for you")

        st.info("""
        💡 Example questions:
        - What is the average salary?
        - Show the top 5 rows by revenue
        - How many missing values are there?
        - What is the correlation between age and salary?
        """)

        user_question = st.text_input("Type your question here:")

        if st.button("🔍 Get Answer") and user_question:
            with st.spinner("AI is thinking and writing code..."):
                code, result, fig, error = query_dataframe(df, user_question)

            st.subheader("🧠 Code Generated by AI")
            st.code(code, language="python")

            if error:
                st.error(f"⚠️ Something went wrong: {error}")
                st.caption("Try rephrasing your question")
            else:
                if result is not None:
                    st.subheader("✅ Answer")
                    st.write(result)
                if fig is not None:
                    st.subheader("📊 Chart")
                    st.pyplot(fig)

    # TAB 3 — Report Generation
    with tab3:
        st.header("📄 AI Business Insights Report")
        st.caption("Get a professional consulting-style report on your entire dataset")

        if st.button("🚀 Generate Report"):
            with st.spinner("AI is analyzing your data and writing the report..."):
                report = generate_report(df)

            st.markdown("---")
            st.markdown(report)
            st.markdown("---")

            with st.spinner("Preparing PDF..."):
                pdf_path = export_pdf(report)

            with open(pdf_path, "rb") as f:
                st.download_button(
                    label="📥 Download Report as PDF",
                    data=f,
                    file_name="ai_analysis_report.pdf",
                    mime="application/pdf"
                )

# Landing screen — shown before file upload
else:
    st.info("👈 Start by uploading a CSV or Excel file from the left sidebar")

    st.markdown("""
    ### 🚀 What This App Does:

    | Feature | Description |
    |---|---|
    | 📊 Auto Analysis | Instant stats, charts, and correlations |
    | 💬 Ask Your Data | Type questions in plain English |
    | 📄 Generate Report | Professional AI-written business report |
    | 📥 PDF Export | Download your report |

    ### 🎯 Built With:
    - **GPT-4o** — for natural language understanding and report writing
    - **Pandas** — for data processing
    - **Streamlit** — for the web interface
    - **Matplotlib & Seaborn** — for charts
    """)